"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var utility_1 = require("./utility");
exports.is = utility_1.is;
exports.merge = utility_1.merge;
exports.format = utility_1.format;
exports.removeItem = utility_1.removeItem;
exports.eventCoord = utility_1.eventCoord;
exports.list = utility_1.list;
exports.randomID = utility_1.randomID;
var storage_1 = require("./storage");
exports.session = storage_1.session;
exports.cookie = storage_1.cookie;
